In [1]:
import xarray as xr
import numpy as np
import pandas as pd

In [2]:
# local path

local_path ='Reanalysis/all_variables/all_variables_1990_1_26.nc'
#gusts = xr.open_dataset('Reanalysis/gust/*.nc')

servor_path = '/work/FAC/FGSE/IDYST/tbeucler/default/raw_data/ECMWF/ERA5/fabien2/ERA5/ERA5_1990_relative_humidity.nc'

relative_humidity = xr.open_dataset(servor_path)

In [3]:
relative_humidity.longitude
relative_humidity['longitude'] = relative_humidity['longitude'].where(relative_humidity['longitude'] >= 0, relative_humidity['longitude'] + 360)

In [5]:
# --> make a function
tracks_path_servor = '/work/FAC/FGSE/IDYST/tbeucler/default/raw_data/ECMWF/WS_fabien/storms_dates.txt'

tracks = pd.read_csv(tracks_path_servor, sep='\t', header=None)
#lon = tracks[5, 0:11]
#lon= np.array(tracks[5])
lon = tracks[5][40:47].to_numpy()
lonx = [float(obj.replace(',','.')) for obj in lon]
lat = tracks[6][40:47].to_numpy()
latx = np.array([float(obj.replace(',','.')) for obj in lat])

In [6]:
# square --> make a function

pos = arr = np.stack((lonx, latx), axis=-1)

tc_irad = np.empty((len(pos), 4))
tc_irad[:,0]=pos[:,0]-3
tc_irad[:,1]=pos[:,0]+3
tc_irad[:,2]=pos[:,1]-3
tc_irad[:,3]=pos[:,1]+3

In [137]:
first_20.sel(longitude=slice(335,345))

<xarray.Dataset>
Dimensions:    (longitude: 41, latitude: 149, time: 128)
Coordinates:
  * longitude  (longitude) float32 335.0 335.2 335.5 335.8 ... 344.5 344.8 345.0
  * latitude   (latitude) float32 71.4 71.15 70.9 70.65 ... 34.9 34.65 34.4
  * time       (time) datetime64[ns] 1990-02-01 ... 1990-02-28T21:00:00
Data variables: (12/26)
    u10        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    v10        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    d2m        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    t2m        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    cbh        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    cape       (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    ...         ...
    mcc        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    sd         (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    sp         (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    tcc        (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    tp         (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
    totalx     (time, latitude, longitude) float32 dask.array<chunksize=(8, 149, 41), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2023-10-04 19:04:38 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [8]:
first_20 = relative_humidity.sel(time=slice('1990-01-01', '1990-01-28'))
LONE, LONW, LATN, LATS = tc_irad[0,:]
print(tc_irad)

first_20 = first_20.sel(latitude=slice(LATS,LATN), longitude=slice(LONE,LONW))
first_20

[[334.849609 340.849609  56.918022  62.918022]
 [335.004578 341.004578  56.822754  62.822754]
 [335.662262 341.662262  56.513908  62.513908]
 [336.791138 342.791138  55.781734  61.781734]
 [338.671143 344.671143  55.060493  61.060493]
 [340.122467 346.122467  54.625305  60.625305]
 [340.889618 346.889618  54.151302  60.151302]]


<xarray.Dataset>
Dimensions:    (longitude: 24, latitude: 24, level: 13, time: 224)
Coordinates:
  * longitude  (longitude) float32 335.0 335.2 335.5 335.8 ... 340.2 340.5 340.8
  * latitude   (latitude) float32 62.75 62.5 62.25 62.0 ... 57.5 57.25 57.0
  * level      (level) int32 70 100 150 200 250 300 400 500 600 700 850 925 1000
  * time       (time) datetime64[ns] 1990-01-01 ... 1990-01-28T21:00:00
Data variables:
    r          (time, level, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-10-19 08:46:46 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [9]:
relative_humidity.longitude

<xarray.DataArray 'longitude' (longitude: 1440)>
array([0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5925e+02, 3.5950e+02,
       3.5975e+02], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
Attributes:
    units:      degrees_east
    long_name:  longitude